---
title: "Learning"
author: "Rostools"
format: html
---

```{r setup}
#| message: false
#| warning: false


library("tidyverse")

post_meal_data <- read.csv2(here::here("data/post-meal-insulin.csv"))
```





## Writing R code

2+2


```{r}
2+2
```


## About me 
- David Vadsholt
- SDCN

My **name** is *David*. 

___

## Simple code
```{r}
3*3
```
## Testing for git

This is some random words


## Showing the data
```{r}
post_meal_data

glimpse(post_meal_data)
```

## Plot one continous variable
```{r}
#| fig-cap: "Distribution of BMI"
#| label: fig-bmi-histo
ggplot(post_meal_data, aes(x=BMI)) +
  geom_histogram(na.rm = FALSE)
```


see @fig-bmi-histo


## Exercise: discrete plots
```{r}
#| fig-cap: "Groups"
#| label: fig-group-bar
ggplot(post_meal_data, aes(x = Group)) +
geom_bar()
```

See @fig-group-bar above for a cool plot!

## Plotting two discrete variables
```{r}
ggplot(post_meal_data, aes(x=Group,fill=as.character(glykemi)))+
  geom_bar(position = position_dodge())
```


